spring:
  profiles:
#    active: dev
#    active: test
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mc.refillCard.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: refillCard

logging:
  level:
    org.springframework.web: info
    com.mc.refillCard: debug


#阿奇索密钥和token 调用接口使用
agiso:
  appSecret: ak6mr75ettb7yktzv7spspwu322f374y
  AccssToken: TbAlds5gt3bhurg6zsupfhvecndpxszavyxwch9tx62atd9y5s

#蜀山密钥和商户ID 调用接口使用
shushan:
  appSecret: y3htuqkbk8awjlf
  merchantID: 17860


fuli:
  appKey: 1wqyNXf90RGYCwTPojXh7BKAPBmUcn36/YCIABCq2I0QWjLKWJXQ96Txd4ZTszsF
  sysSecret: a7f8f390c8bf42b0a2da34caceb8915b
  url: http://openapi.fulu.com/api/getway

#百度地图api
baiduApi:
  ak: V16EnpeKlyqxe1hGi7iIOPfWKRtvc9fj